# Calculator API 配置示例文件
# 复制此文件为 application.yml 并根据需要修改配置

# Spring Boot 应用配置
spring:
  application:
    name: calculator-api
  
  # JSON 序列化配置
  jackson:
    serialization:
      indent-output: true  # 格式化输出JSON
    date-format: yyyy-MM-dd HH:mm:ss  # 日期格式
    time-zone: UTC  # 时区设置
    default-property-inclusion: non-null  # 忽略null值

# 服务器配置
server:
  port: 8080  # 服务端口，可根据需要修改

# 日志配置
logging:
  level:
    root: INFO  # 根日志级别
    com.calculator.api: INFO  # 应用日志级别，可设置为DEBUG进行调试
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"  # 控制台日志格式，包含请求ID追踪

# Actuator 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # 暴露的端点，生产环境建议只暴露health
      base-path: /actuator  # 监控端点基础路径
  endpoint:
    health:
      show-details: when-authorized  # 健康检查详情显示策略
  info:
    env:
      enabled: true  # 启用环境信息
    java:
      enabled: true  # 启用Java信息
    os:
      enabled: true  # 启用操作系统信息

# 应用信息配置
info:
  app:
    name: Calculator API
    description: Calculator API Service with Spring Boot
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 21

# 生产环境配置建议：
# 1. 修改server.port为生产环境端口
# 2. 设置logging.level.root为WARN或ERROR
# 3. 限制management.endpoints.web.exposure.include只包含health
# 4. 配置适当的安全策略 