# E-commerce Platform API 配置文件

# Spring Boot 应用配置
spring:
  application:
    name: ecommerce-platform
  
  # 数据源配置 - H2内存数据库
  datasource:
    url: jdbc:h2:mem:ecommerce_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
  # H2控制台配置（开发环境）
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # 开发环境自动创建表结构
    show-sql: true  # 显示SQL语句
    properties:
      hibernate:
        format_sql: true  # 格式化SQL语句
        use_sql_comments: true  # 显示SQL注释
  
  # JSON 序列化配置
  jackson:
    serialization:
      indent-output: true  # 格式化输出JSON
    date-format: yyyy-MM-dd HH:mm:ss  # 日期格式
    time-zone: Asia/Shanghai  # 时区设置
    default-property-inclusion: non-null  # 忽略null值

# 服务器配置
server:
  port: 8080  # 服务端口

# 日志配置
logging:
  level:
    root: INFO  # 根日志级别
    com.ecommerce: INFO  # 应用日志级别
    org.hibernate.SQL: DEBUG  # SQL日志级别
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 参数绑定日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"

# Actuator 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # 暴露的端点
      base-path: /actuator  # 监控端点基础路径
  endpoint:
    health:
      show-details: when-authorized  # 健康检查详情显示策略

# 应用信息配置
info:
  app:
    name: E-commerce Platform API
    description: E-commerce Platform API Service with Spring Boot and DDD
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 21

# 业务配置
ecommerce:
  # 结算配置
  settlement:
    cron: "0 0 2 * * ?"  # 每天凌晨2点执行结算
    enabled: true
  
  # 货币配置
  currency:
    default: CNY
    precision: 2  # 金额精度（小数位数）
    
  # 订单配置
  order:
    timeout-minutes: 30  # 订单超时时间（分钟）

# 生产环境配置建议：
# 1. 修改server.port为生产环境端口
# 2. 设置logging.level.root为WARN或ERROR
# 3. 限制management.endpoints.web.exposure.include只包含health
# 4. 配置适当的安全策略 