# E-commerce Platform API Configuration

spring:
  application:
    name: ecommerce-platform
  profiles:
    active: mock
  jackson:
    serialization:
      indent-output: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non-null
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO
    com.ecommerce: INFO
    com.ecommerce.api.aspect.RequestLoggingAspect: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"
  file:
    name: logs/ecommerce-platform.log
    max-size: 100MB
    max-history: 30

# Security Configuration
security:
  rate-limit:
    enabled: true
    max-requests-per-minute: 100
  validation:
    max-string-length: 1000
    max-request-size: 10485760  # 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# Application Information
info:
  app:
    name: E-commerce Platform API
    description: E-commerce Platform API Service with Spring Boot and DDD
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 21

# API Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    default-models-expand-depth: 2
    display-request-duration: true
    doc-expansion: none
    urls:
      - name: "All APIs"
        url: "/v3/api-docs"
      - name: "V1 APIs"
        url: "/v3/api-docs/v1"
      - name: "V2 APIs"
        url: "/v3/api-docs/v2"
      - name: "Public APIs"
        url: "/v3/api-docs/public"
  show-actuator: false


# Business Configuration
ecommerce:
  settlement:
    cron: "0 0 2 * * ?"
    enabled: true
  currency:
    default: CNY
    precision: 2
  order:
    timeout-minutes: 30

---
# Mock Environment Configuration
spring:
  config:
    activate:
      on-profile: mock

---
# MySQL Production Environment Configuration
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false 