# E-commerce Platform API Configuration File

# Spring Boot Application Configuration
spring:
  application:
    name: ecommerce-platform
  
  # Data Source Configuration - H2 In-Memory Database
  datasource:
    url: jdbc:h2:mem:ecommerce_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    
  # H2 Console Configuration (Development Environment)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Auto-create table structure in development environment
    show-sql: true  # Display SQL statements
    properties:
      hibernate:
        format_sql: true  # Format SQL statements
        use_sql_comments: true  # Display SQL comments
  
  # JSON Serialization Configuration
  jackson:
    serialization:
      indent-output: true  # Format JSON output
    date-format: yyyy-MM-dd HH:mm:ss  # Date format
    time-zone: Asia/Shanghai  # Timezone setting
    default-property-inclusion: non-null  # Ignore null values

# Server Configuration
server:
  port: 8080  # Service port

# Logging Configuration
logging:
  level:
    root: INFO  # Root log level
    com.ecommerce: INFO  # Application log level
    org.hibernate.SQL: DEBUG  # SQL log level
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Parameter binding log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId:-}] %logger{36} - %msg%n"

# Actuator Monitoring Endpoint Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Exposed endpoints
      base-path: /actuator  # Monitoring endpoint base path
  endpoint:
    health:
      show-details: when-authorized  # Health check detail display policy

# Application Information Configuration
info:
  app:
    name: E-commerce Platform API
    description: E-commerce Platform API Service with Spring Boot and DDD
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 21

# Business Configuration
ecommerce:
  # Settlement Configuration
  settlement:
    cron: "0 0 2 * * ?"  # Execute settlement daily at 2 AM
    enabled: true
  
  # Currency Configuration
  currency:
    default: CNY
    precision: 2  # Amount precision (decimal places)
    
  # Order Configuration
  order:
    timeout-minutes: 30  # Order timeout (minutes)

# Production Environment Configuration Recommendations:
# 1. Modify server.port to production environment port
# 2. Set logging.level.root to WARN or ERROR
# 3. Limit management.endpoints.web.exposure.include to only include health
# 4. Configure appropriate security policies 